var main ="this is the main file";

var hello = function(){
    console.log("I did a lot of work on this main page")
};

console.log("a")
console.log("b")
console.log("c")
console.log("d")
console.log("e")
console.log("f")
console.log("g")
console.log("h")
console.log("i")
console.log("j")
console.log("k")
console.log("l")
console.log("m")
console.log("n")
console.log("oh")
console.log("pee")
console.log("queen")
console.log("r")
console.log("s")
console.log("t")
console.log("u")
console.log("v")
console.log("w")
console.log("x")
console.log("y")
console.log("z")